### ISSUE TITLE
chatgpt_bot: queue jobs created, but state will stay in pending, no response

### ISSUE THREAD

**Issue by JGStyle** [singleflo/free_addons_odoo#1]
When I ask OdooBot a question, It will generate the job in the queue, however the jobs will stay in pending. 
- I have entered the api_key
- I have set workers to 6
- I have set server_wide modules to base,web,queue_job
- I have set [queue_job], channels = root:2
- The 'Worker WorkerJobRunner alive' message appears in the logs
- I have set the status to chatgpt enabled in settings > users > Mitchell admin
- I am using odoo 15 on my local machine and running on localhost, maybe that is the problem?

As visible on the screenshot, the jobs are correctly created when sending a message to odoobot, however the jobs stay in pending and I do not get a response from odoobot
<img width="1214" alt="image" src="https://user-images.githubusercontent.com/51161233/227158308-9e9e8177-6b5e-4c5d-b419-9736afebd45c.png">

**Comment by crottolo** [comment]
hae you see the queue job app?

**Comment by crottolo** [comment]
no response
